spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  config:
    import: optional:file:.env[.properties]
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_SMTP_LOGIN}
    password: ${BREVO_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG

app:
  cookie:
    secure: false
    same-site: Lax
  cors:
    allowed-origins: http://localhost:5173
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000
  frontend-url: http://localhost:5173
  brevo:
    from-email: ${BREVO_FROM_EMAIL}
